# Generated by Django 3.1.5 on 2021-01-08 08:49

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(default='In Progress', max_length=11),
        ),
        migrations.AlterField(
            model_name='claim',
            name='insurance_cover_note_pdf',
            field=models.FileField(upload_to='pdfs/', validators=[dashboard.models.Claim.validate_pdf_file_extension]),
        ),
    ]
