# Generated by Django 3.1.5 on 2021-01-10 09:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210109_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='insurance_cover_note_pdf',
            field=models.FileField(upload_to=dashboard.models.Claim.pdf_user_directory_path),
        ),
        migrations.AlterField(
            model_name='claim',
            name='photo',
            field=models.ImageField(upload_to=dashboard.models.Claim.img_user_directory_path),
        ),
    ]
